sudo: required
services:
  - docker

before_install:
  - docker build -t vasiltehanov/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vasiltehanov/docker-react npm run test -- --watchAll=false
